name: Publish binaries to Releases

on:
  push:
    branches: [ master ]
    tags:
      - release-v*
    
  pull_request:
    branches: [ master ]
    tags:
      - release-v*

jobs:
  build-linux-gnu:
    name: Build for linux/GNU 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup target add x86_64-unknown-linux-gnu
    - run: cargo build --release --target=x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v1
      with:
        name: flowy_linux_gnu
        path: target/release-linux/flowy

  release-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: flowy_macos
        path: target/release/flowy

  release-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: flowy_windows
        path: target/release/flowy.exe
        
  push-to-releases:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v1.3.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           path: target/release
           release-type: rust
           package-name: release-please-action
